apiRules:
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGLES1
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGLES3
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGL
- exclude: 
    uidRegex: ^OpenTK\.Graphics\.OpenGL\.Compatibility
