### YamlMime:ManagedReference
items:
- uid: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX
  commentId: T:OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX
  id: GLXHyperpipeConfigSGIX
  parent: OpenTK.Graphics.Glx
  children:
  - OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.Channel
  - OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.ParticipationType
  - OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.PipeName
  - OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.TimeSlice
  langs:
  - csharp
  - vb
  name: GLXHyperpipeConfigSGIX
  nameWithType: GLXHyperpipeConfigSGIX
  fullName: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX
  type: Struct
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: GLXHyperpipeConfigSGIX
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 459
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  syntax:
    content: public struct GLXHyperpipeConfigSGIX
    content.vb: Public Structure GLXHyperpipeConfigSGIX
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.PipeName
  commentId: F:OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.PipeName
  id: PipeName
  parent: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX
  langs:
  - csharp
  - vb
  name: PipeName
  nameWithType: GLXHyperpipeConfigSGIX.PipeName
  fullName: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.PipeName
  type: Field
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: PipeName
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 461
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  syntax:
    content: public byte* PipeName
    return:
      type: System.Byte*
    content.vb: Public PipeName As Byte*
- uid: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.Channel
  commentId: F:OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.Channel
  id: Channel
  parent: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX
  langs:
  - csharp
  - vb
  name: Channel
  nameWithType: GLXHyperpipeConfigSGIX.Channel
  fullName: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.Channel
  type: Field
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: Channel
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 462
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  syntax:
    content: public int Channel
    return:
      type: System.Int32
    content.vb: Public Channel As Integer
- uid: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.ParticipationType
  commentId: F:OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.ParticipationType
  id: ParticipationType
  parent: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX
  langs:
  - csharp
  - vb
  name: ParticipationType
  nameWithType: GLXHyperpipeConfigSGIX.ParticipationType
  fullName: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.ParticipationType
  type: Field
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: ParticipationType
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 463
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  syntax:
    content: public uint ParticipationType
    return:
      type: System.UInt32
    content.vb: Public ParticipationType As UInteger
- uid: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.TimeSlice
  commentId: F:OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.TimeSlice
  id: TimeSlice
  parent: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX
  langs:
  - csharp
  - vb
  name: TimeSlice
  nameWithType: GLXHyperpipeConfigSGIX.TimeSlice
  fullName: OpenTK.Graphics.Glx.GLXHyperpipeConfigSGIX.TimeSlice
  type: Field
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: TimeSlice
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 464
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  syntax:
    content: public int TimeSlice
    return:
      type: System.Int32
    content.vb: Public TimeSlice As Integer
references:
- uid: OpenTK.Graphics.Glx
  commentId: N:OpenTK.Graphics.Glx
  href: OpenTK.html
  name: OpenTK.Graphics.Glx
  nameWithType: OpenTK.Graphics.Glx
  fullName: OpenTK.Graphics.Glx
  spec.csharp:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Graphics
    name: Graphics
    href: OpenTK.Graphics.html
  - name: .
  - uid: OpenTK.Graphics.Glx
    name: Glx
    href: OpenTK.Graphics.Glx.html
  spec.vb:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Graphics
    name: Graphics
    href: OpenTK.Graphics.html
  - name: .
  - uid: OpenTK.Graphics.Glx
    name: Glx
    href: OpenTK.Graphics.Glx.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Byte*
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte*
  nameWithType: byte*
  fullName: byte*
  nameWithType.vb: Byte*
  fullName.vb: Byte*
  name.vb: Byte*
  spec.csharp:
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '*'
  spec.vb:
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '*'
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
