### YamlMime:ManagedReference
items:
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  commentId: T:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  id: GLXFBConfigIDSGIX
  parent: OpenTK.Graphics.Glx
  children:
  - OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.#ctor(System.UIntPtr)
  - OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.XID
  - OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit(OpenTK.Graphics.Glx.GLXFBConfigIDSGIX)~System.UIntPtr
  - OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit(System.UIntPtr)~OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  langs:
  - csharp
  - vb
  name: GLXFBConfigIDSGIX
  nameWithType: GLXFBConfigIDSGIX
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  type: Struct
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: GLXFBConfigIDSGIX
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 376
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  summary: A GLX GLXFBConfigIDSGIX handle.
  example: []
  syntax:
    content: public struct GLXFBConfigIDSGIX
    content.vb: Public Structure GLXFBConfigIDSGIX
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.XID
  commentId: F:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.XID
  id: XID
  parent: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  langs:
  - csharp
  - vb
  name: XID
  nameWithType: GLXFBConfigIDSGIX.XID
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.XID
  type: Field
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: XID
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 381
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  summary: The underlying XID.
  example: []
  syntax:
    content: public nuint XID
    return:
      type: System.UIntPtr
    content.vb: Public XID As UIntPtr
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.#ctor(System.UIntPtr)
  commentId: M:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.#ctor(System.UIntPtr)
  id: '#ctor(System.UIntPtr)'
  parent: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  langs:
  - csharp
  - vb
  name: GLXFBConfigIDSGIX(nuint)
  nameWithType: GLXFBConfigIDSGIX.GLXFBConfigIDSGIX(nuint)
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.GLXFBConfigIDSGIX(nuint)
  type: Constructor
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: .ctor
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 387
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  summary: Constructs a new GLXFBConfigIDSGIX wrapper struct from an XID.
  example: []
  syntax:
    content: public GLXFBConfigIDSGIX(nuint xid)
    parameters:
    - id: xid
      type: System.UIntPtr
      description: The XID of the GLXFBConfigIDSGIX.
    content.vb: Public Sub New(xid As UIntPtr)
  overload: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.#ctor*
  nameWithType.vb: GLXFBConfigIDSGIX.New(UIntPtr)
  fullName.vb: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.New(System.UIntPtr)
  name.vb: New(UIntPtr)
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit(OpenTK.Graphics.Glx.GLXFBConfigIDSGIX)~System.UIntPtr
  commentId: M:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit(OpenTK.Graphics.Glx.GLXFBConfigIDSGIX)~System.UIntPtr
  id: op_Explicit(OpenTK.Graphics.Glx.GLXFBConfigIDSGIX)~System.UIntPtr
  parent: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  langs:
  - csharp
  - vb
  name: explicit operator nuint(GLXFBConfigIDSGIX)
  nameWithType: GLXFBConfigIDSGIX.explicit operator nuint(GLXFBConfigIDSGIX)
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.explicit operator nuint(OpenTK.Graphics.Glx.GLXFBConfigIDSGIX)
  type: Operator
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: op_Explicit
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 392
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  syntax:
    content: public static explicit operator nuint(GLXFBConfigIDSGIX handle)
    parameters:
    - id: handle
      type: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
    return:
      type: System.UIntPtr
    content.vb: Public Shared Narrowing Operator CType(handle As GLXFBConfigIDSGIX) As UIntPtr
  overload: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit*
  nameWithType.vb: GLXFBConfigIDSGIX.CType(GLXFBConfigIDSGIX)
  fullName.vb: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.CType(OpenTK.Graphics.Glx.GLXFBConfigIDSGIX)
  name.vb: CType(GLXFBConfigIDSGIX)
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit(System.UIntPtr)~OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  commentId: M:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit(System.UIntPtr)~OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  id: op_Explicit(System.UIntPtr)~OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  parent: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  langs:
  - csharp
  - vb
  name: explicit operator GLXFBConfigIDSGIX(nuint)
  nameWithType: GLXFBConfigIDSGIX.explicit operator GLXFBConfigIDSGIX(nuint)
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.explicit operator OpenTK.Graphics.Glx.GLXFBConfigIDSGIX(nuint)
  type: Operator
  source:
    remote:
      path: src/OpenTK.Graphics/Types.cs
      branch: pal2-work
      repo: https://github.com/opentk/opentk.git
    id: op_Explicit
    path: opentk/src/OpenTK.Graphics/Types.cs
    startLine: 393
  assemblies:
  - OpenTK.Graphics
  namespace: OpenTK.Graphics.Glx
  syntax:
    content: public static explicit operator GLXFBConfigIDSGIX(nuint xid)
    parameters:
    - id: xid
      type: System.UIntPtr
    return:
      type: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
    content.vb: Public Shared Narrowing Operator CType(xid As UIntPtr) As GLXFBConfigIDSGIX
  overload: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit*
  nameWithType.vb: GLXFBConfigIDSGIX.CType(UIntPtr)
  fullName.vb: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.CType(System.UIntPtr)
  name.vb: CType(UIntPtr)
references:
- uid: OpenTK.Graphics.Glx
  commentId: N:OpenTK.Graphics.Glx
  href: OpenTK.html
  name: OpenTK.Graphics.Glx
  nameWithType: OpenTK.Graphics.Glx
  fullName: OpenTK.Graphics.Glx
  spec.csharp:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Graphics
    name: Graphics
    href: OpenTK.Graphics.html
  - name: .
  - uid: OpenTK.Graphics.Glx
    name: Glx
    href: OpenTK.Graphics.Glx.html
  spec.vb:
  - uid: OpenTK
    name: OpenTK
    href: OpenTK.html
  - name: .
  - uid: OpenTK.Graphics
    name: Graphics
    href: OpenTK.Graphics.html
  - name: .
  - uid: OpenTK.Graphics.Glx
    name: Glx
    href: OpenTK.Graphics.Glx.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.UIntPtr
  commentId: T:System.UIntPtr
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uintptr
  name: nuint
  nameWithType: nuint
  fullName: nuint
  nameWithType.vb: UIntPtr
  fullName.vb: System.UIntPtr
  name.vb: UIntPtr
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.#ctor*
  commentId: Overload:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.#ctor
  href: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.html#OpenTK_Graphics_Glx_GLXFBConfigIDSGIX__ctor_System_UIntPtr_
  name: GLXFBConfigIDSGIX
  nameWithType: GLXFBConfigIDSGIX.GLXFBConfigIDSGIX
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.GLXFBConfigIDSGIX
  nameWithType.vb: GLXFBConfigIDSGIX.New
  fullName.vb: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.New
  name.vb: New
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit*
  commentId: Overload:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.op_Explicit
  name: explicit operator
  nameWithType: GLXFBConfigIDSGIX.explicit operator
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.explicit operator
  nameWithType.vb: GLXFBConfigIDSGIX.CType
  fullName.vb: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.CType
  name.vb: CType
  spec.csharp:
  - name: explicit
  - name: " "
  - name: operator
- uid: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  commentId: T:OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
  parent: OpenTK.Graphics.Glx
  href: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX.html
  name: GLXFBConfigIDSGIX
  nameWithType: GLXFBConfigIDSGIX
  fullName: OpenTK.Graphics.Glx.GLXFBConfigIDSGIX
